services:
  postgres:
    build:
      context: ./Docker
      dockerfile: postgres.Dockerfile
    image: "cs223-proj1"
    container_name: '${PG_CONTAINER_NAME}'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGDATA: '${PGDATA}'
    ports:
      - "5432:5432"
    restart: unless-stopped

