services:
  postgres:
    build:
      context: ./Docker
      dockerfile: postgres.Dockerfile
    image: "cs223-proj1"
    command: postgres -c 'max_connections=${PG_MAX_CONNECTIONS}'
    container_name: '${PG_CONTAINER_NAME}'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGDATA: '${PGDATA}'
    ports:
      - "${PG_HOST_PORT}:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16g
    shm_size: 20g
